---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomixp
# description will be included in the image's metadata
description: Experimental bluebuild image with XFCE and labwc aiming to create an "XP" like experience.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: rpm-ostree
    install:
      #labwc bits
      - labwc
      - wlroots
      - xorg-x11-server-Xwayland
      - xfce4-panel
      - xfdesktop
      - xfce4-settings
      - xfce4-terminal
      - thunar
      - thunar-archive-plugin
      - xfconf
      - sddm
      - swaybg
      - wlr-randr
      - network-manager-applet
      - pavucontrol
      - mesa-va-drivers-freeworld
      - mesa-vdpau-drivers-freeworld

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - xfceconf.sh
      
  - type: systemd
    system:
      enabled:
        - sddm