---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomixp
# description will be included in the image's metadata
description: Experimental bluebuild image with XFCE aiming to create an "XP" like experience.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: rpm-ostree
    install:
      - xfce4-session
      - xfce4-panel
      - xfdesktop
      - xfwm4
      - xfconf
      - xfce4-terminal
      - xorg-x11-server-Xorg
      - xorg-x11-xinit
      - xorg-x11-drv-amdgpu
      - xorg-x11-drv-libinput
      - network-manager-applet
      - thunar
      - thunar-archive-plugin
      - network-manager-applet
      - lightdm
      - lightdm-gobject-devel
      - libX11-devel
      - xfce4-panel-devel
      - libxfce4ui-devel
      - libxfce4util-devel
      - python3-pillow
      - gtk-murrine-engine
      - gtk2-engines
      - pavucontrol
      - fastfetch
      - cmake
      - gcc
      - fakeroot
      - glib2-devel
      - rpmdevtools
      - gtk3-devel
      - gstreamer1-devel

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - xfceconf.sh
      
  - type: systemd
    system:
      enabled:
        - lightdm