---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomixp
# description will be included in the image's metadata
description: Experimental bluebuild image with XFCE aiming to create an "XP" like experience.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/winblues/vauxite-minimal
image-version: 43

modules:
  - type: rpm-ostree
    install:
        - gtk-murrine-engine
        - gtk2-engines
        - adwaita-gtk2-theme
        - alsa-utils
        - blueman
        - gtk-xfce-engine
        - xfce4-whiskermenu-plugin
        - xarchiver
        - mate-system-monitor
        - xscreensaver-extras
        - xscreensaver-extras-gss
        - qt6ct
        - wine-tahoma-fonts

  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
    install:
      - steam
      - gamescope
      - gamemode
      - mangohud

  - type: files
    files:
     - source: system
       destination: /

  - type: script
    scripts:
      - os-info.sh
      - theme.sh
      
  - type: systemd
    system:
      enabled:
        - sddm
        - xptc-apply